# Generated by Django 4.1 on 2022-08-31 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_topic_room_host_messeage_room_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messeage',
            new_name='Message',
        ),
    ]
